name: Terraform

on:
  pull_request:
    paths:
      - 'terraform-libvirt/**'
      - '.github/workflows/terraform.yml'
  push:
    branches:
      - main
    paths:
      - 'terraform-libvirt/**'
      - '.github/workflows/terraform.yml'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    name: Terraform Plan
    if: github.event_name == 'pull_request'
    uses: zavestudios/platform-pipelines/.github/workflows/terraform-plan.yml@main
    with:
      tf_working_dir: terraform-libvirt
      terraform_version: latest

  apply:
    name: Terraform Apply
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: zavestudios/platform-pipelines/.github/workflows/terraform-apply.yml@main
    with:
      tf_working_dir: terraform-libvirt
      terraform_version: latest
